const CURRENCYS = ['USD', 'EUR'];
const BASE_CURRENCY = process.env.REACT_APP_BASE_CURRENCY;
const BASE_URL = process.env.REACT_APP_RATES_URL;
const UKRAINE_URL = process.env.REACT_APP_UKRAINE_URL;
const UKRAINE_UAH_URL =process.env.REACT_APP_UKRAINE_UAH_URL;

export { CURRENCYS, BASE_CURRENCY, BASE_URL, UKRAINE_URL, UKRAINE_UAH_URL };